version: '3.8'

services:
  web:
    build: .
    ports:
    # map port
      - "5000:5000"
    environment:
    # set env variable
      - FLASK_APP=core/server.py
    command: sh -c 
            "rm -f core/store.sqlite3 && 
            flask db upgrade -d core/migrations/ && 
            pytest -vvv -s tests/"

            # remove store.sqlite3 if it exists
            # run db migrations
            # run tests