version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=core/server.py
    volumes:
      - .:/app
    command: sh -c "rm -f core/store.sqlite3 && flask db upgrade -d core/migrations/ && pytest -vvv -s tests/"